version: '3.4'

services:

  app:
    image: php-swoole:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: 'bin/console mezzio:swoole:start -w 1'
    ports:
      - 30000:30000
